name: Build & Push Docker Images

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx (modern multi-platform builder)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub securely using repository secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Writer image
      - name: Build & Push Writer
        uses: docker/build-push-action@v5
        with:
          context: .
          file: API.Writer/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-practice-writer:latest

      # Build and push Reader image
      - name: Build & Push Reader
        uses: docker/build-push-action@v5
        with:
          context: .
          file: API.Reader/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-practice-reader:latest
