name: Build & Push Docker Images

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Writer
        uses: docker/build-push-action@v5
        with:
          context: .
          file: API.Writer/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-practice:writer

      - name: Build & Push Reader
        uses: docker/build-push-action@v5
        with:
          context: .
          file: API.Reader/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-practice:reader

            - name: Delete old images from Docker Hub (keep latest only)
        run: |
          REPO=${{ secrets.DOCKERHUB_USERNAME }}/devops-practice
          for service in writer reader; do
            # Fetch all tags for the service
            tags=$(curl -s -u "${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_TOKEN }}" \
              "https://hub.docker.com/v2/repositories/$REPO/tags/?page_size=100" \
              | jq -r '.results[].name' | grep $service)

            # Keep the most recent tag (plain "writer"/"reader"), delete others
            for tag in $tags; do
              if [ "$tag" != "$service" ]; then
                echo "Deleting $REPO:$tag"
                curl -s -X DELETE -u "${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_TOKEN }}" \
                  "https://hub.docker.com/v2/repositories/$REPO/tags/$tag/"
              fi
            done
          done

