name: Build & Push Docker Images

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Writer
        uses: docker/build-push-action@v5
        with:
          context: .
          file: API.Writer/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-practice:writer

      - name: Build & Push Reader
        uses: docker/build-push-action@v5
        with:
          context: .
          file: API.Reader/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-practice:reader
